language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update --stable -n

install:
  - travis_retry composer install --no-suggest --no-interaction

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: composer clover

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
