name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  analysis:
    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "7.4"
        operating-system:
          - "ubuntu-latest"

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: PHP Installation
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: bcmath

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

      - name: "Install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' }}
        run: "composer install --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

      - name: Validate
        run: |
          composer validate
          composer normalize --dry-run

  tests:
    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
          - "locked"
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: PHP Installation
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: bcmath

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

      - name: "Install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' }}
        run: "composer install --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

      - name: Test
        run: vendor/bin/phpunit
